name: CI
on: [push]
jobs:
  standard-checks: 
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm ci

      - name: Run Eslint
        run: npm run ci:lint

      - name: Run Tests
        run: npm run ci:test

      - name: Bundle and Output
        run: npm run build

      - name: Vercel Production Deployment
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        on:
          push:
            branches:
              - main
        jobs:
          Deploy-Production:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v2
              - name: Install Vercel CLI
                run: npm install --global vercel@latest
              - name: Pull Vercel Environment Information
                run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
              - name: Build Project Artifacts
                run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
              - name: Deploy Project Artifacts to Vercel
                run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}